image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - publish

before_script:
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  - (if [[ -n "${DOCKERHUB_USER}" ]]; then docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASSWORD}"; fi)

after_script:
  - docker logout "${CI_REGISTRY}"
  - (if [[ -n "${DOCKERHUB_USER}" ]]; then docker logout; fi)

.set-build-image-with-commit: &set-build-image-with-commit
  - BUILD_IMAGE=${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${IMAGE_NAME}-${CI_COMMIT_SHORT_SHA}

.set-build-args-for-nginx: &set-build-args-for-nginx
  - BUILD_ARGS=" --build-arg BASE_IMAGE=\"${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/php-nginx/${BASE_IMAGE}\""
  - BUILD_ARGS="${BUILD_ARGS} --build-arg CONFIGS_PATH=\"configs-nginx\""

.set-build-args-for-apache: &set-build-args-for-apache
  - BUILD_ARGS=" --build-arg BASE_IMAGE=\"${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/php-apache/${BASE_IMAGE}\""
  - BUILD_ARGS="${BUILD_ARGS} --build-arg CONFIGS_PATH=\"configs-apache\""

.build-image: &build-image
  - eval "
      docker build --pull --force-rm ${BUILD_ARGS}
        -t "${BUILD_IMAGE}" . >build.log 2>&1
      " || ((tail -50 build.log | nl); exit 1)
  - docker push "${BUILD_IMAGE}"

.build-log-artifacts: &build-log-artifacts
  artifacts:
    paths:
      - build.log
    expire_in: 6 hrs

.test-image: &test-image
  - cd tests
  - chmod +x *.sh
  - echo "WORDPRESS_IMAGE=${BUILD_IMAGE}" >.env
  - ./tests.sh

.set-publish-gitlab-image: &set-publish-gitlab-image
  - PUBLISH_IMAGE=${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${GITLAB_IMAGE}

.set-publish-gitlab-image-with-commit: &set-publish-gitlab-image-with-commit
  - PUBLISH_IMAGE=${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${GITLAB_IMAGE}-${CI_COMMIT_SHORT_SHA}

.set-publish-dockerhub-image: &set-publish-dockerhub-image
  - PUBLISH_IMAGE=${DOCKERHUB_IMAGE}

.set-publish-dockerhub-latest-image: &set-publish-dockerhub-latest-image
  - PUBLISH_IMAGE=${DOCKERHUB_LATEST_IMAGE}

.publish-image: &publish-image
  - docker pull "${BUILD_IMAGE}"
  - docker tag "${BUILD_IMAGE}" "${PUBLISH_IMAGE}"
  - docker push "${PUBLISH_IMAGE}"

.wordpress-php-nginx-7-4: &wordpress-php-nginx-7-4
  variables:
    BASE_IMAGE: php-nginx:7.4
    IMAGE_NAME: wordpress:php-nginx-7.4
    GITLAB_IMAGE: wordpress:php-nginx-7.4
    DOCKERHUB_IMAGE: ${DOCKERHUB_USER}/wordpress:php-nginx-7.4
    DOCKERHUB_LATEST_IMAGE: ${DOCKERHUB_USER}/wordpress:latest
  rules:
    - changes:
        - configs-nginx/*
        - Dockerfile
        - scripts/*
        - tests/*

build-wordpress-php-nginx-7.4:
  stage: build
  <<: *wordpress-php-nginx-7-4
  script:
    - set -x
    - *set-build-image-with-commit
    - *set-build-args-for-nginx
    - *build-image
  <<: *build-log-artifacts

test-wordpress-php-nginx-7.4:
  stage: test
  <<: *wordpress-php-nginx-7-4
  image: 
    name: docker/compose:latest
  script:
    - set -x
    - *set-build-image-with-commit
    - *test-image
  needs:
    - job: build-wordpress-php-nginx-7.4

publish-wordpress-php-nginx-7.4:
  stage: publish
  <<: *wordpress-php-nginx-7-4
  script:
    - set -x
    - *set-build-image-with-commit
    - *set-publish-gitlab-image
    - *publish-image
    - *set-publish-dockerhub-image
    - *publish-image
    - *set-publish-dockerhub-latest-image
    - *publish-image
  needs:
    - job: test-wordpress-php-nginx-7.4

.wordpress-php-nginx-7-3: &wordpress-php-nginx-7-3
  variables:
    BASE_IMAGE: php-nginx:7.3
    IMAGE_NAME: wordpress:php-nginx-7.3
    GITLAB_IMAGE: wordpress:php-nginx-7.3
    DOCKERHUB_IMAGE: ${DOCKERHUB_USER}/wordpress:php-nginx-7.3
  rules:
    - changes:
        - configs-nginx/*
        - Dockerfile
        - scripts/*
        - tests/*

build-wordpress-php-nginx-7.3:
  stage: build
  <<: *wordpress-php-nginx-7-3
  script:
    - set -x
    - *set-build-image-with-commit
    - *set-build-args-for-nginx
    - *build-image
  <<: *build-log-artifacts

test-wordpress-php-nginx-7.3:
  stage: test
  <<: *wordpress-php-nginx-7-3
  image: 
    name: docker/compose:latest
  script:
    - set -x
    - *set-build-image-with-commit
    - *test-image
  needs:
    - job: build-wordpress-php-nginx-7.3

publish-wordpress-php-nginx-7.3:
  stage: publish
  <<: *wordpress-php-nginx-7-3
  script:
    - set -x
    - *set-build-image-with-commit
    - *set-publish-gitlab-image
    - *publish-image
    - *set-publish-dockerhub-image
    - *publish-image
  needs:
    - job: test-wordpress-php-nginx-7.3

.wordpress-php-apache-7-4: &wordpress-php-apache-7-4
  variables:
    BASE_IMAGE: php-apache:7.4
    IMAGE_NAME: wordpress:php-apache-7.4
    GITLAB_IMAGE: wordpress:php-apache-7.4
    DOCKERHUB_IMAGE: ${DOCKERHUB_USER}/wordpress:php-apache-7.4
  rules:
    - changes:
        - configs-apache/*
        - Dockerfile
        - scripts/*
        - tests/*

build-wordpress-php-apache-7.4:
  stage: build
  <<: *wordpress-php-apache-7-4
  script:
    - set -x
    - *set-build-image-with-commit
    - *set-build-args-for-apache
    - *build-image
  <<: *build-log-artifacts

test-wordpress-php-apache-7.4:
  stage: test
  <<: *wordpress-php-apache-7-4
  image: 
    name: docker/compose:latest
  script:
    - set -x
    - *set-build-image-with-commit
    - *test-image
  needs:
    - job: build-wordpress-php-apache-7.4

publish-wordpress-php-apache-7.4:
  stage: publish
  <<: *wordpress-php-apache-7-4
  script:
    - set -x
    - *set-build-image-with-commit
    - *set-publish-gitlab-image
    - *publish-image
    - *set-publish-dockerhub-image
    - *publish-image
  needs:
    - job: test-wordpress-php-apache-7.4

.wordpress-php-apache-7-3: &wordpress-php-apache-7-3
  variables:
    BASE_IMAGE: php-apache:7.3
    IMAGE_NAME: wordpress:php-apache-7.3
    GITLAB_IMAGE: wordpress:php-apache-7.3
    DOCKERHUB_IMAGE: ${DOCKERHUB_USER}/wordpress:php-apache-7.3
  rules:
    - changes:
        - configs-apache/*
        - Dockerfile
        - scripts/*
        - tests/*

build-wordpress-php-apache-7.3:
  stage: build
  <<: *wordpress-php-apache-7-3
  script:
    - set -x
    - *set-build-image-with-commit
    - *set-build-args-for-apache
    - *build-image
  <<: *build-log-artifacts

test-wordpress-php-apache-7.3:
  stage: test
  <<: *wordpress-php-apache-7-3
  image: 
    name: docker/compose:latest
  script:
    - set -x
    - *set-build-image-with-commit
    - *test-image
  needs:
    - job: build-wordpress-php-apache-7.3

publish-wordpress-php-apache-7.3:
  stage: publish
  <<: *wordpress-php-apache-7-3
  script:
    - set -x
    - *set-build-image-with-commit
    - *set-publish-gitlab-image
    - *publish-image
    - *set-publish-dockerhub-image
    - *publish-image
  needs:
    - job: test-wordpress-php-apache-7.3
